name: Run Automated Tests 

on:
# This would run the pipeline every night at 11pm
# schedule:
#   - cron: '0 23 * * *'
  workflow_dispatch:

  push:
    branches:
    - 'master'

env:
  HOME_URL: ${{ vars.HOME_URL }}

jobs:
  run-ui-automated-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5.8.2
      with:
        # working-directory: cd..
        # build: npm run build
        # start: npm start
        runTests: true
        browser: chrome


    # - name: Executing the tests
    #   run: npm run allTests

    - name: Uploading mochawesome json files
      uses: actions/upload-artifact@master
      with:
        name: mochawesome-json
        path: cypress/reports/
        
    - name: Uploading Videos
      uses: actions/upload-artifact@master
      with:
        name: videos
        path: cypress/videos/
        
  generating-report:
      needs: [run-ui-automated-tests]
      if: always()
      runs-on: ubuntu-latest
      steps:
        - name: Installing Dependencies
          run: |
            npm install mochawesome --save-dev
            npm install mochawesome-merge --save-dev
            
          
        - name: Downloading mochawesome json files
          uses: actions/download-artifact@master
          with:
            name: mochawesome-json
            path: cypress/reports/
          
          
        - name: Merging Mochawesome Json Reports
          run: |
              mkdir test-report
              npx mochawesome-merge "./cypress/reports/mochawesome-report/mochawesome*.json"  > test-report/test-report.json
              npx marge test-report/test-report.json
              
        - name: Generating HTML Report
          uses: actions/upload-artifact@master
          with:
            name: test-report
            path: ./mochawesome-report/
      
  
